### PR TITLE
fixed param of extract-pot

### PR DESCRIPTION
**Pull request by lexoyo**

### CODE REVIEW

**Comment by lexoyo** [comment]
this causes these errors
https://github.com/mozilla/i18n-abide/issues/93

**Comment by lexoyo** [comment]
@SirAnthony @azten what do you think of this fix?

**Comment by SirAnthony** [comment]
Dunno, I remember, I did something with this tool, but this was thousand ages ago, I do not remember why I did it.

**Comment by lexoyo** [comment]
Hi @zaach 
Do you think someone will have time to review this PR?
Thx a lot :)

**Comment by lexoyo** [comment]
Bump @zaach :accept: :)

**Comment by ozum** [comment]
Hi,

Is there a possibility to urge this pr to be merged into repository? In our projects, i18n-abide does not work without this patch.

Thx.

**Comment by ozum** [comment]
Bump. Could someone please review this PR?

**Comment by ozum** [comment]
Finally. Thank you @zaach

**Comment by lexoyo** [comment]
My pleasure @ozum !
:sunny:

**Pull request merged**
